// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://fiqq5pqiqzbddnnlhuuva44dqm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fanwy746rvb5rlojqdugykgm7e",
    "aws_content_delivery_bucket": "ciccia-lab-website-20200507221357-hostingbucket-cicciac",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3aouq5s3rqf5t.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:6c8dc45b-43e0-4c2b-ad21-df8c4dbea3f0",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "b74e3d7f47c948a087d9f21ef8e0e440",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
