// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "genomicstore-cicenv",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:a495d0f5-704e-4b1e-ab0e-a77c5186a645",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_I7i313VbB",
    "aws_user_pools_web_client_id": "44kksa1r2mmkslk8bt5guqeb32",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "genomic",
            "endpoint": "https://koqmz59m3e.execute-api.us-east-1.amazonaws.com/cicenv",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
